# -*- coding: utf-8 -*-
import io
def rd(p): return io.open(p, encoding='utf-8').read()
def wr(p, h): io.open(p, 'w', encoding='utf-8').write(h)
def rep(h, name, label):
    o = rd('.fixsi/' + name + '_old.txt'); n = rd('.fixsi/' + name + '_new.txt')
    assert h.count(o) == 1, '%s count %d' % (label, h.count(o))
    return h.replace(o, n)
h = rd('web/index.html')
h = rep(h, 'tabs', 'tabs')
h = rep(h, 'branch', 'branch')
a = rd('.fixsi/fn_anchor.txt')
assert h.count(a) == 1, 'fn anchor %d' % h.count(a)
h = h.replace(a, rd('.fixsi/fn_new.txt') + a)
wr('web/index.html', h)
h = rd('test/hardening.ts')
pa = rd('.fixsi/pin_anchor.txt')
assert h.count(pa) == 1, 'pin anchor %d' % h.count(pa)
h = h.replace(pa, rd('.fixsi/dom_pin.txt') + pa)
wr('test/hardening.ts', h)
print('si2 applied')
