# -*- coding: utf-8 -*-
import io
def rd(p): return io.open(p, encoding='utf-8').read()
def wr(p, h): io.open(p, 'w', encoding='utf-8').write(h)
def rep(h, name, label, expect=1):
    o = rd('.fixp5/' + name + '_old.txt'); n = rd('.fixp5/' + name + '_new.txt')
    c = h.count(o)
    assert c == expect, '%s count %d != %d' % (label, c, expect)
    return h.replace(o, n)
h = rd('web/index.html')
h = rep(h, 'go', 'go')
h = rep(h, 'sse', 'sse')
h = rep(h, 'l2', 'l2')
h = rep(h, 'from', 'from')
h = rep(h, 'banner', 'banner')
h = rep(h, 'm1', 'm1')
h = rep(h, 'api', 'api')
h = rep(h, 'wire', 'wire')
h = rep(h, 'hint', 'hint')
h = rep(h, 'note', 'note', 2)
wr('web/index.html', h)
h = rd('src/admin.ts')
h = rep(h, 'ovvoid', 'ovvoid')
h = rep(h, 'ovlogs', 'ovlogs')
wr('src/admin.ts', h)
print('p5 ok')
