# -*- coding: utf-8 -*-
import io
def rd(p): return io.open(p, encoding='utf-8').read()
def wr(p, h): io.open(p, 'w', encoding='utf-8').write(h)
def rep(h, name, label, expect=1):
    o = rd('.fixp8/' + name + '_old.txt'); n = rd('.fixp8/' + name + '_new.txt')
    c = h.count(o)
    assert c == expect, '%s count %d != %d' % (label, c, expect)
    return h.replace(o, n)
h = rd('src/ratelimit.ts')
h = rep(h, 'rl_ip', 'rl_ip')
h = rep(h, 'rl_note', 'rl_note')
wr('src/ratelimit.ts', h)
h = rd('src/admin.ts')
h = rep(h, 'adm_local', 'adm_local')
h = rep(h, 'adm_shut', 'adm_shut')
h = rep(h, 'adm_ho', 'adm_ho')
h = rep(h, 'adm_tk', 'adm_tk')
wr('src/admin.ts', h)
h = rd('src/gateway.ts')
h = rep(h, 'gw_exp', 'gw_exp')
h = rep(h, 'gw_models', 'gw_models')
wr('src/gateway.ts', h)
h = rd('src/app.ts')
h = rep(h, 'app_imp', 'app_imp')
h = rep(h, 'app_ct', 'app_ct')
wr('src/app.ts', h)
h = rd('README.md')
h = rep(h, 'rd', 'readme')
wr('README.md', h)
h = rd('test/e2e.ts')
o = rd('.fixp8/e2e_old.txt'); n = rd('.fixp8/e2e_new.txt')
assert h.count(o) == 1, 'e2e brute %d' % h.count(o)
h = h.replace(o, n)
wr('test/e2e.ts', h)
h = rd('test/hardening.ts')
h = rep(h, 'hard_ready', 'hard_ready')
h = rep(h, 'hard_blk', 'hard_blk')
wr('test/hardening.ts', h)
print('p7 all ok')
